"""
Template-based report rendering.

The LLM returns a compact JSON "report spec" (headline, narrative text, and the
numbers to show). Python does the financial math and renders the HTML/SVG from
fixed templates. This keeps the LLM output small, which is what makes the
report fast: generation time scales with output tokens.
"""

import html
import math
from datetime import date

# BLS median usual weekly earnings for high school graduates x 52. The prompt's
# bachelor's figure (77636) is the same measure; both match
# src/app/constants/college_related_constants.ts.
HS_SALARY = 46_748
LOAN_RATE = 0.065  # STUDENT_LOAN_INTEREST_RATE in college_related_constants.ts
REPAYMENT_YEARS = 20
BLS_SALARY_CAP = 239_200  # OEWS top-codes annual wages; a median at the cap may be higher

FIGURES_NOTICE = (
    "Every figure in this report (salaries, earnings, costs, and debt) is a median or average across many "
    "people, not a prediction for you. The AI writing this report can mix up these typical figures with "
    "your own situation, so where it says what you earn, pay, or will owe, read it as the typical figure "
    "for that occupation, school, or program."
)

DISCLAIMER = (
    "Generated by AI using data from BLS (May 2024), College Scorecard, and O*NET. "
    "For informational purposes only, not financial or career advice. "
    "AI analysis may contain errors; verify figures before making decisions. Generated {today}."
)

REPORT_SPEC_SYSTEM_PROMPT = """You write the content for a personalized college and career report. You receive raw data from tool calls and the user's intake profile. The page layout, CSS, charts, and financial math are handled by code. You only return JSON content. Keep it compact: no HTML, no markdown.

RESPOND WITH ONLY VALID JSON matching this shape:
{
  "summary": "1-2 sentence plain text takeaway for chat",
  "headline": "bold 1-2 sentence personalized takeaway",
  "baseline_salary": 46748,
  "baseline_label": "High school diploma",
  "options": [
    {"name": "Electrician", "short_label": "Electrician", "education": "4-5 yr apprenticeship", "years_in_school": 0, "annual_cost": 0, "expected_salary": 61590, "note": "Bright outlook"}
  ],
  "sections": [
    {
      "title": "Section heading",
      "what_it_means": "One 'What this means for you' sentence: a concrete takeaway for this user, not a description of the section.",
      "bullets": ["optional short point"],
      "table": {"columns": ["School", "Net price"], "rows": [["UF", "$9,400"]]},
      "chart": {"title": "Median salary", "x_label": "Annual Salary ($)", "y_label": "Occupation", "unit": "usd", "bars": [{"label": "Electrician", "value": 61590}]}
    }
  ],
  "limitations": ["short honest caveat"]
}

FIELD RULES:
- options: one entry per path being compared (career, school, or program). Code computes education cost (annual_cost x years_in_school), opportunity cost, total investment, monthly loan payment (6.53% over 20 years), and payoff timeline, and renders the financial table and payoff chart. Do not compute these yourself.
  * years_in_school: years of full-time school still required (0 for no school). annual_cost: annual net price or tuition in dollars (0 if none).
  * expected_salary: annual salary in dollars from the tool data.
  * Include the baseline as an option only when the path format asks for it as a row (it will show zero cost).
- baseline_salary: 46748 (HS diploma) unless the user gave a current salary; then use it. baseline_label names it.
- sections: 2-4 sections ordered by importance to this user. table, chart, and bullets are each optional; include only what adds value. Do not repeat the financial breakdown. Short chart labels (e.g. "CO Mines"). chart unit is one of: usd, percent, years, number.
- Table cells are short display strings, already formatted.
- Never use the words "major" or "break-even". Say "degree" or "program", and "payoff timeline".
- Salaries, debt, and costs are medians: say "median", never "average". Salaries span all experience levels, so never "starting" or "entry-level".
- Use only figures from the tool data or path1_options. If a figure isn't there, don't estimate it; say it in words.
- Don't assume the user's past school counts toward a new career; how much transfers depends on the field and program.
- For income-based net price data, highlight the bracket closest to the user's situation if known.

PATH-SPECIFIC CONTENT (intake "path_type"):
path1 (college vs vocational vs work): when path1_options is given, it is the five options, built by code: years of school, median student debt, and median salary for each. Code renders the charts and financial breakdown, so return "options": [] and no charts or tables. Write two sections from those numbers, never changing or recomputing them: how the options compare on median salary and years of school, and what each education path costs in median debt and time out of work. The main thing to catch: when the chosen occupation's graduate_school_required is true (e.g. law, medicine), lead the headline with it and state its years_beyond_bachelors as years beyond a bachelor's, plus the added debt and extra years out of work; when it is false, say no graduate school is required. When a row has user_numbers true, it is the chosen occupation with the user's own tuition or expected salary (cost_basis says which); compare it with the national median row and say which figures are theirs. Without path1_options, options are exactly five rows: HS diploma baseline (zero cost, baseline salary), Cashier, Electrician, Bachelor's degree median (expected_salary 77636, the BLS median for bachelor's degree holders), user's chosen occupation.
path2 (comparing schools): options are the top 5 schools ranked by the user's chosen metric. A section table shows ONLY the metrics the user toggled in compare_metrics.
path3 (comparing programs at school): options are the programs. A section compares school-specific earnings (College Scorecard) with national occupation salary (BLS), labeling sources, plus bright outlook status from O*NET.
path4 (compare career tracks): options are the careers. Use current_position, education_level, current_field, and current_role for context (gap from current role), with years_in_school from each career's typical years of school. If compare_to_current is "no", options are only the named careers (no current-job row) and the baseline is current_salary_value as "Your current salary" when given, else the high school median.
path5 (path to career): options are the realistic routes to the target. One section is a roadmap: bullets as ordered steps with timeline, plus the education the target requires.
"""


# Shape the path1 report model must return; the API enforces it (structured output).
_TEXT = {"type": "string"}
PATH1_REPORT_SCHEMA = {
    "type": "object",
    "properties": {
        "headline": _TEXT,
        "sections": {"type": "array", "items": {
            "type": "object",
            "properties": {"title": _TEXT, "bullets": {"type": "array", "items": _TEXT}, "what_it_means": _TEXT},
            "required": ["title", "bullets", "what_it_means"],
            "additionalProperties": False,
        }},
        "limitations": {"type": "array", "items": _TEXT},
    },
    "required": ["headline", "sections", "limitations"],
    "additionalProperties": False,
}

# Path1 only (college vs trade vs working now). The prompt above still serves
# paths 2-5; each path gets its own prompt as it's reworked, and shared rules
# get pulled out once every path's evals pass.
PATH1_REPORT_PROMPT = """You write the text of a report for someone deciding between college, a trade, or working right away. Code has already built the five options in path1_options (years of school, median student debt, median salary; rows marked user_numbers use the user's own tuition or salary) and renders the salary chart, the financial breakdown with payoff timelines, and notes on sources and assumptions. Your text explains what those numbers mean; the reader sees the chart and table next to it.

Return only JSON:
{"headline": "...", "sections": [{"title": "...", "bullets": ["..."], "what_it_means": "..."}], "limitations": ["..."]}

- headline: 1-2 sentences, also shown as the chat reply, so it must stand on its own. State the main takeaway itself; never describe the report or the comparison ("This report...", "Comparing...").
  * a user_numbers row exists: lead with the user's expected salary and total cost against the national median, using its gaps. E.g. "With your numbers, becoming a teacher means $60,000 in total cost, $35,000 more than the national median debt, for an expected salary of $50,000, $12,000 below the national median."
  * otherwise, graduate_school_required true: lead with years_beyond_bachelors as years beyond a bachelor's and the total years of school, then what those years buy (median salary) and cost (median debt). E.g. "Becoming a school counselor typically takes 2 years beyond a bachelor's (6 in total) and $30,000 more in median debt, for $8,000 more in median salary."
  * otherwise, graduate_school_required false: say no graduate school is required, then the years of school, median salary, and median debt. E.g. "Teachers need no graduate school: typically 4 years of school and about $25,000 in median debt for a median salary of about $62,000."
- sections: two. (1) Pay and years of school. (2) Cost: median debt and years out of work. The reader already sees every row in the table, so bullets compare options instead of restating them, using the supplied gaps, e.g. "School counselors earn $8,000 more in median salary than bachelor's holders, but typically need 2 more years of school and $30,000 more in median debt." what_it_means: one concrete takeaway for this person.
- limitations: 1-2 caveats specific to this comparison. The report already says figures are medians and how payoff is counted; don't repeat that.

Rules:
- Use only numbers from path1_options; never compute one. For differences use the supplied gaps: salary_gap_vs_bachelors and debt_gap_vs_bachelors on the chosen occupation, salary_gap_vs_median and debt_gap_vs_median on a user_numbers row (negative means less). Use each figure once.
- Each row's debt is its total. A graduate row's debt already includes a bachelor's; its extra debt is debt_gap_vs_bachelors.
- Put "median" with every national salary or debt figure. The user's own figures (rows marked user_numbers, and their gaps) say "your" instead, never "median". National figures describe occupations, never the user's own pay.
- Write dollar amounts with commas and no decimals ($61,690).
- Years of school are typical, not guaranteed: say "typically" (e.g. "typically 6 years of school").
- The payoff timeline already counts debt, loan interest, and earnings given up while in school; don't describe what it includes or leaves out.
- For user_numbers rows, say which figures are the user's and compare them with the national median row. When there is one, the headline leads with that comparison (e.g. their expected salary and total cost against the national median).
- Say "degree" or "program", never "major"; "payoff timeline", never "break-even".
"""

def _esc(value) -> str:
    return html.escape(str(value), quote=True)


def _num(value, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _usd(value: float) -> str:
    return f"${value:,.0f}"


def _fmt(value: float, unit: str) -> str:
    if unit == "usd":
        return _usd(value)
    if unit == "percent":
        return f"{value:.0f}%"
    if unit == "years":
        return f"{value:.1f} yrs"
    return f"{value:,.0f}"


def monthly_payment(principal: float, rate: float = LOAN_RATE, years: int = REPAYMENT_YEARS) -> float:
    if principal <= 0:
        return 0.0
    r = rate / 12
    n = years * 12
    return principal * r / (1 - (1 + r) ** -n)


def compute_financials(option: dict, baseline_salary: float) -> dict:
    """Options built in code (path1) carry total "debt" and follow the web app's
    math: total = debt + loan interest + earnings given up while in school.
    LLM-built options carry annual_cost and leave interest out."""
    years = _num(option.get("years_in_school"))
    opportunity_cost = baseline_salary * years
    if "debt" in option:
        education_cost = _num(option.get("debt"))
        interest = monthly_payment(education_cost) * REPAYMENT_YEARS * 12 - education_cost
        total = education_cost + max(interest, 0) + opportunity_cost
    else:
        education_cost = _num(option.get("annual_cost")) * years
        total = education_cost + opportunity_cost
    salary = _num(option.get("expected_salary"))
    delta = salary - baseline_salary
    if total == 0:
        payoff = 0.0
    elif delta > 0:
        # Counted from the first day of school: years in school, then the
        # years of higher pay it takes to recover the total investment.
        payoff = years + total / delta
    else:
        payoff = None
    return {
        "education_cost": education_cost,
        "opportunity_cost": opportunity_cost,
        "total_investment": total,
        "monthly_payment": monthly_payment(education_cost),
        "salary": salary,
        "payoff_years": payoff,
    }


def _nice_max(value: float) -> float:
    """Round the axis max up to 1, 2, 2.5, or 5 x 10^n so ticks are round numbers."""
    if value <= 0:
        return 1.0
    step = value / 4
    mag = 10 ** math.floor(math.log10(step))
    for m in (1, 2, 2.5, 5, 10):
        if step <= m * mag:
            return m * mag * 4
    return value


def _short(label: str, limit: int = 20) -> str:
    return label if len(label) <= limit else label[: limit - 1].rstrip() + "…"


def bar_chart(title: str, x_label: str, y_label: str, bars: list[dict], unit: str = "number", source: str = "") -> str:
    """Horizontal bar chart: labels left of bars, values right, sorted desc, gridlines."""
    bars = sorted(
        ({"label": str(b.get("label", "")), "value": _num(b.get("value"))} for b in bars),
        key=lambda b: b["value"],
        reverse=True,
    )
    if not bars:
        return ""
    left, right, top, bar_h, gap = 150, 90, 20, 28, 12
    width = 700
    plot_w = width - left - right
    plot_h = len(bars) * (bar_h + gap) - gap
    height = top + plot_h + 50
    max_v = _nice_max(max(b["value"] for b in bars))
    ticks = 4
    parts = [f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="{_esc(title)}">']
    for i in range(ticks + 1):
        x = left + plot_w * i / ticks
        v = max_v * i / ticks
        parts.append(f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + plot_h}" class="grid"/>')
        parts.append(f'<text x="{x:.1f}" y="{top + plot_h + 16}" class="tick" text-anchor="middle">{_esc(_fmt(v, unit))}</text>')
    for i, b in enumerate(bars):
        y = top + i * (bar_h + gap)
        w = plot_w * max(b["value"], 0) / max_v
        cy = y + bar_h / 2 + 5
        parts.append(f'<text x="{left - 8}" y="{cy:.1f}" class="lbl" text-anchor="end"><title>{_esc(b["label"])}</title>{_esc(_short(b["label"]))}</text>')
        parts.append(f'<rect x="{left}" y="{y}" width="{w:.1f}" height="{bar_h}" class="bar" rx="3"/>')
        parts.append(f'<text x="{left + w + 6:.1f}" y="{cy:.1f}" class="val">{_esc(_fmt(b["value"], unit))}</text>')
    parts.append(f'<text x="{left + plot_w / 2:.1f}" y="{height - 6}" class="axis" text-anchor="middle">{_esc(x_label)}</text>')
    parts.append(
        f'<text x="14" y="{top + plot_h / 2:.1f}" class="axis" text-anchor="middle" '
        f'transform="rotate(-90 14 {top + plot_h / 2:.1f})">{_esc(y_label)}</text>'
    )
    parts.append("</svg>")
    src = f'<span class="src">Source: {_esc(source)}</span>' if source else ""
    return f'<figure><figcaption>{_esc(title)}{src}</figcaption>{"".join(parts)}</figure>'


def _table(columns: list, rows: list) -> str:
    head = "".join(f"<th>{_esc(c)}</th>" for c in columns)
    body = "".join("<tr>" + "".join(f"<td>{_esc(c)}</td>" for c in row) + "</tr>" for row in rows)
    return f'<div class="tbl"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def _financial_section(options: list[dict], baseline_salary: float, baseline_label: str) -> str:
    if not options:
        return ""
    rows = []
    payoff_bars = []
    for opt in options:
        f = compute_financials(opt, baseline_salary)
        payoff = f["payoff_years"]
        payoff_text = "Does not pay off at this salary" if payoff is None else ("Immediate" if payoff == 0 else f"{payoff:.1f} yrs")
        rows.append([
            opt.get("name", ""),
            opt.get("education", ""),
            _usd(f["education_cost"]),
            _usd(f["opportunity_cost"]),
            _usd(f["total_investment"]),
            _usd(f["monthly_payment"]),
            _usd(f["salary"]),
            payoff_text,
        ])
        if payoff:
            payoff_bars.append({"label": opt.get("short_label") or opt.get("name", ""), "value": payoff})
    table = _table(
        ["Option", "Education", "Education cost", "Opportunity cost", "Total investment",
         "Monthly loan payment", "Expected salary", "Payoff (years from starting school)"],
        rows,
    )
    chart = bar_chart(
        "Payoff timeline: years from the first day of school", "Years from starting school until the cost is recovered", "Option",
        payoff_bars, "years", "Computed from each option's cost and expected salary in the table above",
    )
    debt_based = any("debt" in o for o in options)
    capped = [o.get("name", "") for o in options if _num(o.get("expected_salary")) >= BLS_SALARY_CAP]
    cap_note = (
        f'<p class="note">BLS reports wages above {_usd(BLS_SALARY_CAP)} as {_usd(BLS_SALARY_CAP)}, '
        f'so the real median for {_esc(", ".join(capped))} may be higher.</p>'
        if capped else ""
    )
    cost_notes = "".join(
        f"<li>{_esc(o.get('name', ''))}: {_esc(o['cost_basis'])}</li>"
        for o in options if o.get("cost_basis") and _num(o.get("years_in_school")) > 0
    )
    return (
        '<section><h2>Financial breakdown</h2>'
        f'<p class="note">Baseline: {_esc(baseline_label)} at {_usd(baseline_salary)}/yr. '
        f'Loans at {LOAN_RATE * 100:.1f}% over {REPAYMENT_YEARS} years. '
        + ("Education cost is median student debt (College Scorecard); total investment adds loan interest. "
           if debt_based else "")
        + 'Opportunity cost is baseline earnings given up while in school. '
        'Expected salaries are medians, not starting pay.'
        + (" Rows marked (your numbers) use the tuition and salary you gave instead, as listed below."
           if any(o.get("user_numbers") for o in options) else "")
        + '</p>'
        f"{table}{cap_note}"
        '<p class="note"><strong>About the payoff timeline:</strong> it counts from the first day of school, '
        'assumes full-time school with no income in the meantime, and assumes the median salary right after '
        'graduating. Starting salaries are often lower than the median, so the real payoff usually takes longer.</p>'
        + (f'<p class="note">Education cost sources:</p><ul class="note">{cost_notes}</ul>' if cost_notes else "")
        + f"{chart}</section>"
    )


def _salary_chart(options: list[dict]) -> str:
    """Salary comparison for code-built options, labeled with its sources."""
    # Only national figures belong in a chart titled median salary.
    bars = [
        {"label": o.get("short_label") or o.get("name", ""), "value": o.get("expected_salary")}
        for o in options if not o.get("user_numbers")
    ]
    return (
        '<section><h2>Median salary by option</h2>'
        + bar_chart(
            "Median annual salary", "Median annual salary", "Option", bars, "usd",
            "BLS OEWS May 2024 median annual wage (occupations); BLS median weekly earnings x 52 "
            "(high school diploma, bachelor's degree)",
        )
        + "</section>"
    )


def _section(sec: dict) -> str:
    out = [f'<section><h2>{_esc(sec.get("title", ""))}</h2>']
    bullets = sec.get("bullets") or []
    if bullets:
        out.append("<ul>" + "".join(f"<li>{_esc(b)}</li>" for b in bullets) + "</ul>")
    table = sec.get("table")
    if isinstance(table, dict) and table.get("rows"):
        out.append(_table(table.get("columns", []), table["rows"]))
    chart = sec.get("chart")
    if isinstance(chart, dict) and chart.get("bars"):
        out.append(bar_chart(
            chart.get("title", ""), chart.get("x_label", ""), chart.get("y_label", ""),
            chart["bars"], chart.get("unit", "number"),
        ))
    if sec.get("what_it_means"):
        out.append(f'<p class="means"><strong>What this means for you:</strong> {_esc(sec["what_it_means"])}</p>')
    out.append("</section>")
    return "".join(out)


CSS = """
*{box-sizing:border-box}
body{margin:0;background:#fff;color:#1f2937;font:15px/1.6 'Inter',system-ui,sans-serif}
main{max-width:920px;margin:0 auto;padding:24px 16px 48px}
h1{font-size:1.2rem;color:#6b7280;margin:0 0 8px;font-weight:600}
.headline{font-size:1.45rem;font-weight:700;line-height:1.35;margin:0 0 24px}
h2{font-size:1.15rem;margin:0 0 12px;padding-bottom:6px;border-bottom:2px solid #e5e7eb}
section{margin:0 0 32px;page-break-inside:avoid}
.tbl{overflow-x:auto;margin:0 0 16px}
table{border-collapse:collapse;width:100%;font-size:.9rem}
th,td{padding:8px 10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}
th{background:#f3f4f6;font-weight:600;white-space:nowrap}
figure{margin:0 0 16px}
figcaption{font-weight:600;margin:0 0 4px}
.src{display:block;color:#6b7280;font-size:.8rem;font-weight:400}
svg{width:100%;height:auto;font-size:12px}
svg .grid{stroke:#e5e7eb}
svg .bar{fill:#2563eb}
svg .lbl,svg .val{fill:#1f2937}
svg .tick{fill:#6b7280;font-size:11px}
svg .axis{fill:#374151;font-weight:600}
.means{background:#eff6ff;border-left:4px solid #2563eb;padding:10px 12px;margin:0}
.note{color:#4b5563;font-size:.9rem}
.notice{border-bottom:1px solid #e5e7eb;padding-bottom:12px;margin:0 0 20px;color:#374151;font-size:.9rem;font-weight:700}
footer{border-top:1px solid #e5e7eb;padding-top:12px;color:#6b7280;font-size:.8rem}
.save-btn{position:fixed;top:12px;right:12px;background:#2563eb;color:#fff;border:0;border-radius:6px;padding:8px 14px;font:600 .85rem system-ui,sans-serif;cursor:pointer}
@media print{.save-btn{display:none}section{page-break-before:auto}}
"""

SAVE_BUTTON = (
    '<button class="save-btn" onclick="(function(){var a=document.createElement(\'a\');'
    "a.href='data:text/html,'+encodeURIComponent(document.documentElement.outerHTML);"
    "a.download='next-right-step-report.html';a.click()})()\">Save Report</button>"
)


def render_report(spec: dict, fixed_options: list[dict] | None = None) -> str:
    """fixed_options: options built in code (path1). They replace the LLM's
    options and get a code-rendered salary chart."""
    baseline_salary = _num(spec.get("baseline_salary"), HS_SALARY) or HS_SALARY
    baseline_label = spec.get("baseline_label") or "High school diploma"
    if fixed_options:
        baseline_salary, baseline_label = HS_SALARY, "High school diploma"
    options = fixed_options or [o for o in spec.get("options") or [] if isinstance(o, dict)]
    sections = [s for s in spec.get("sections") or [] if isinstance(s, dict)]
    limitations = spec.get("limitations") or []

    body = [
        f'<p class="notice">{_esc(FIGURES_NOTICE)}</p>',
        "<h1>Your Next Right Step report</h1>",
        f'<p class="headline">{_esc(spec.get("headline", ""))}</p>',
    ]
    if fixed_options:
        # Code renders the path1 charts with sources; drop any the LLM added.
        sections = [{k: v for k, v in sec.items() if k != "chart"} for sec in sections]
        body.append(_salary_chart(fixed_options))
    body.extend(_section(s) for s in sections)
    body.append(_financial_section(options, baseline_salary, baseline_label))
    if limitations:
        body.append(
            "<section><h2>Limitations</h2><ul>"
            + "".join(f"<li>{_esc(item)}</li>" for item in limitations)
            + "</ul></section>"
        )
    body.append(f"<footer>{_esc(DISCLAIMER.format(today=date.today().strftime('%B %d, %Y')))}</footer>")

    return (
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        "<title>Next Right Step Report</title>"
        '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">'
        f"<style>{CSS}</style></head><body>{SAVE_BUTTON}<main>{''.join(body)}</main></body></html>"
    )
