"""
Template-based report rendering.

The LLM returns a compact JSON "report spec": the headline, the text, and which
option rows (options.py) to compare. Python does the financial math and renders
the HTML/SVG from fixed templates and the rows' own numbers. This keeps the LLM
output small, which is what makes the report fast: generation time scales with
output tokens.
"""

import html
import math
from datetime import date

# BLS median usual weekly earnings for high school graduates x 52. The prompt's
# bachelor's figure (77636) is the same measure; both match
# src/app/constants/college_related_constants.ts.
HS_SALARY = 46_748
LOAN_RATE = 0.065  # STUDENT_LOAN_INTEREST_RATE in college_related_constants.ts
REPAYMENT_YEARS = 20
BLS_SALARY_CAP = 239_200  # OEWS top-codes annual wages; a median at the cap may be higher

FIGURES_NOTICE = (
    "Every figure in this report (salaries, earnings, costs, and debt) is a median or average across many "
    "people, not a prediction for you. The AI writing this report can mix up these typical figures with "
    "your own situation, so where it says what you earn, pay, or will owe, read it as the typical figure "
    "for that occupation, school, or program."
)

DISCLAIMER = (
    "Generated by AI using data from BLS (May 2024), College Scorecard, and O*NET. "
    "For informational purposes only, not financial or career advice. "
    "AI analysis may contain errors; verify figures before making decisions. Generated {today}."
)

REPORT_PROMPT = """You write the text of a college and career report. Input: the user's intake answers (path_type says their question), option rows built by code, and the gaps between every pair of rows. Code renders the charts, the financial table with payoff timelines, and source notes; you pick the rows and write the words.

- option_ids: the rows that answer their question, in display order.
- headline: the main takeaway in 1-2 sentences; it is also the chat reply. Never describe the report.
- sections: 2-3, most important first. The reader already sees every row in the table, so each bullet compares two or more options ("Lawyers earn $68,124 more in median salary than bachelor's holders"); never one bullet per option restating its numbers. what_it_means: one concrete takeaway. table_metrics: row metrics worth a table here; only the ones the user chose, if they chose any.
- limitations: 1-2 caveats specific to this comparison.

Numbers:
- Use only numbers from the rows and gaps, copied exactly; never compute one. Each gap names the option with the higher salary, debt, or years. Write dollars as $61,690.
- Write for the user: never say "row", "gap", or field names. National figures are medians: say "median salary", "median debt". Rows marked user_numbers hold the user's own figures: say "your".
- Occupation salaries are BLS medians for the whole occupation; school and program salaries are College Scorecard earnings of its graduates.
- Years of school are typical: say "typically".

Per path:
- path1: college vs a trade vs working now. Show every row compare_education_paths returned. The headline states figures: with a user_numbers row, the user's salary and debt against the national median; otherwise whether the chosen occupation needs graduate school, its total years of school, median salary, and median debt, and, if it does, its years beyond a bachelor's and its salary and debt gaps against the bachelor's row.
- path2: compare the schools on the metrics they chose, ranked by rank_by.
- path3: compare the programs: school earnings against national pay for the occupations they lead to.
- path4: compare the careers, and their current job unless compare_to_current is "no". Past school may not count toward a new career.
- path5: a roadmap from their current role to the target: ordered steps with the typical time for each.
"""

_TEXT = {"type": "string"}


def report_schema(rows: list[dict]) -> dict:
    """The shape the report model must return; the API enforces it. option ids
    and metric keys are limited to the rows the model was given."""
    ids = {"type": "string", "enum": [r["option_id"] for r in rows]}
    metrics = sorted({k for r in rows for k in (r.get("metrics") or {}) if k in METRIC_FORMATS})
    metric = {"type": "string", "enum": metrics} if metrics else _TEXT
    return {
        "type": "object",
        "properties": {
            "headline": _TEXT,
            "option_ids": {"type": "array", "items": ids},
            "sections": {"type": "array", "items": {
                "type": "object",
                "properties": {
                    "title": _TEXT,
                    "bullets": {"type": "array", "items": _TEXT},
                    "what_it_means": _TEXT,
                    "table_metrics": {"type": "array", "items": metric},
                },
                "required": ["title", "bullets", "what_it_means", "table_metrics"],
                "additionalProperties": False,
            }},
            "limitations": {"type": "array", "items": _TEXT},
        },
        "required": ["headline", "option_ids", "sections", "limitations"],
        "additionalProperties": False,
    }


# Row metrics the report can show as a table: key -> (column label, unit).
METRIC_FORMATS = {
    "avg_net_price": ("Net price per year", "usd"),
    "tuition_in_state": ("In-state tuition", "usd"),
    "tuition_out_of_state": ("Out-of-state tuition", "usd"),
    "graduation_rate": ("Graduation rate", "percent"),
    "admission_rate": ("Admission rate", "percent"),
    "retention_rate": ("Retention rate", "percent"),
    "loan_repayment_rate_3yr": ("Loan repayment (3 yr)", "percent"),
    "median_debt": ("Median debt", "usd"),
    "earnings_6yr_after_entry": ("Earnings 6 yrs after entry", "usd"),
    "earnings_10yr_after_entry": ("Earnings 10 yrs after entry", "usd"),
    "earnings_1yr_after_graduation": ("Earnings 1 yr after graduating", "usd"),
    "earnings_4yr_after_graduation": ("Earnings 4 yrs after graduating", "usd"),
    "student_size": ("Students", "number"),
    "bright_outlook": ("Bright outlook (O*NET)", "bool"),
}


def _esc(value) -> str:
    return html.escape(str(value), quote=True)


def _num(value, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _usd(value: float) -> str:
    return f"${value:,.0f}"


def _fmt(value: float, unit: str) -> str:
    if unit == "usd":
        return _usd(value)
    if unit == "percent":
        return f"{value:.0f}%"
    if unit == "years":
        return f"{value:.1f} yrs"
    return f"{value:,.0f}"


def monthly_payment(principal: float, rate: float = LOAN_RATE, years: int = REPAYMENT_YEARS) -> float:
    if principal <= 0:
        return 0.0
    r = rate / 12
    n = years * 12
    return principal * r / (1 - (1 + r) ** -n)


def compute_financials(option: dict, baseline_salary: float) -> dict:
    """Follows the web app's math: total = debt + loan interest + earnings given
    up while in school."""
    years = _num(option.get("years_in_school"))
    opportunity_cost = baseline_salary * years
    education_cost = _num(option.get("debt"))
    interest = monthly_payment(education_cost) * REPAYMENT_YEARS * 12 - education_cost
    total = education_cost + max(interest, 0) + opportunity_cost
    salary = _num(option.get("expected_salary"))
    delta = salary - baseline_salary
    if total == 0:
        payoff = 0.0
    elif delta > 0:
        # Counted from the first day of school: years in school, then the
        # years of higher pay it takes to recover the total investment.
        payoff = years + total / delta
    else:
        payoff = None
    return {
        "education_cost": education_cost,
        "opportunity_cost": opportunity_cost,
        "total_investment": total,
        "monthly_payment": monthly_payment(education_cost),
        "salary": salary,
        "payoff_years": payoff,
    }


def _nice_max(value: float) -> float:
    """Round the axis max up to 1, 2, 2.5, or 5 x 10^n so ticks are round numbers."""
    if value <= 0:
        return 1.0
    step = value / 4
    mag = 10 ** math.floor(math.log10(step))
    for m in (1, 2, 2.5, 5, 10):
        if step <= m * mag:
            return m * mag * 4
    return value


def _short(label: str, limit: int = 20) -> str:
    return label if len(label) <= limit else label[: limit - 1].rstrip() + "…"


def bar_chart(title: str, x_label: str, y_label: str, bars: list[dict], unit: str = "number", source: str = "") -> str:
    """Horizontal bar chart: labels left of bars, values right, sorted desc, gridlines."""
    bars = sorted(
        ({"label": str(b.get("label", "")), "value": _num(b.get("value"))} for b in bars),
        key=lambda b: b["value"],
        reverse=True,
    )
    if not bars:
        return ""
    left, right, top, bar_h, gap = 150, 90, 20, 28, 12
    width = 700
    plot_w = width - left - right
    plot_h = len(bars) * (bar_h + gap) - gap
    height = top + plot_h + 50
    max_v = _nice_max(max(b["value"] for b in bars))
    ticks = 4
    parts = [f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="{_esc(title)}">']
    for i in range(ticks + 1):
        x = left + plot_w * i / ticks
        v = max_v * i / ticks
        parts.append(f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + plot_h}" class="grid"/>')
        parts.append(f'<text x="{x:.1f}" y="{top + plot_h + 16}" class="tick" text-anchor="middle">{_esc(_fmt(v, unit))}</text>')
    for i, b in enumerate(bars):
        y = top + i * (bar_h + gap)
        w = plot_w * max(b["value"], 0) / max_v
        cy = y + bar_h / 2 + 5
        parts.append(f'<text x="{left - 8}" y="{cy:.1f}" class="lbl" text-anchor="end"><title>{_esc(b["label"])}</title>{_esc(_short(b["label"]))}</text>')
        parts.append(f'<rect x="{left}" y="{y}" width="{w:.1f}" height="{bar_h}" class="bar" rx="3"/>')
        parts.append(f'<text x="{left + w + 6:.1f}" y="{cy:.1f}" class="val">{_esc(_fmt(b["value"], unit))}</text>')
    parts.append(f'<text x="{left + plot_w / 2:.1f}" y="{height - 6}" class="axis" text-anchor="middle">{_esc(x_label)}</text>')
    parts.append(
        f'<text x="14" y="{top + plot_h / 2:.1f}" class="axis" text-anchor="middle" '
        f'transform="rotate(-90 14 {top + plot_h / 2:.1f})">{_esc(y_label)}</text>'
    )
    parts.append("</svg>")
    src = f'<span class="src">Source: {_esc(source)}</span>' if source else ""
    return f'<figure><figcaption>{_esc(title)}{src}</figcaption>{"".join(parts)}</figure>'


def _table(columns: list, rows: list) -> str:
    head = "".join(f"<th>{_esc(c)}</th>" for c in columns)
    body = "".join("<tr>" + "".join(f"<td>{_esc(c)}</td>" for c in row) + "</tr>" for row in rows)
    return f'<div class="tbl"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def _financial_section(options: list[dict], baseline_salary: float, baseline_label: str) -> str:
    if not options:
        return ""
    rows = []
    payoff_bars = []
    for opt in options:
        f = compute_financials(opt, baseline_salary)
        payoff = f["payoff_years"]
        payoff_text = "Does not pay off at this salary" if payoff is None else ("Immediate" if payoff == 0 else f"{payoff:.1f} yrs")
        rows.append([
            opt.get("name", ""),
            opt.get("education", ""),
            _usd(f["education_cost"]),
            _usd(f["opportunity_cost"]),
            _usd(f["total_investment"]),
            _usd(f["monthly_payment"]),
            _usd(f["salary"]),
            payoff_text,
        ])
        if payoff:
            payoff_bars.append({"label": opt.get("short_label") or opt.get("name", ""), "value": payoff})
    table = _table(
        ["Option", "Education", "Education cost", "Opportunity cost", "Total investment",
         "Monthly loan payment", "Expected salary", "Payoff (years from starting school)"],
        rows,
    )
    chart = bar_chart(
        "Payoff timeline: years from the first day of school", "Years from starting school until the cost is recovered", "Option",
        payoff_bars, "years", "Computed from each option's cost and expected salary in the table above",
    )
    capped = [o.get("name", "") for o in options if _num(o.get("expected_salary")) >= BLS_SALARY_CAP]
    cap_note = (
        f'<p class="note">BLS reports wages above {_usd(BLS_SALARY_CAP)} as {_usd(BLS_SALARY_CAP)}, '
        f'so the real median for {_esc(", ".join(capped))} may be higher.</p>'
        if capped else ""
    )
    cost_notes = "".join(
        f"<li>{_esc(o.get('name', ''))}: {_esc(o['cost_basis'])}</li>"
        for o in options if o.get("cost_basis") and _num(o.get("years_in_school")) > 0
    )
    return (
        '<section><h2>Financial breakdown</h2>'
        f'<p class="note">Baseline: {_esc(baseline_label)} at {_usd(baseline_salary)}/yr. '
        f'Loans at {LOAN_RATE * 100:.1f}% over {REPAYMENT_YEARS} years. '
        + "Education cost is median student debt (College Scorecard); total investment adds loan interest. "
        + 'Opportunity cost is baseline earnings given up while in school. '
        'Expected salaries are medians, not starting pay.'
        + (" Rows marked (your numbers) use the tuition and salary you gave instead, as listed below."
           if any(o.get("user_numbers") for o in options) else "")
        + '</p>'
        f"{table}{cap_note}"
        '<p class="note"><strong>About the payoff timeline:</strong> it counts from the first day of school, '
        'assumes full-time school with no income in the meantime, and assumes the median salary right after '
        'graduating. Starting salaries are often lower than the median, so the real payoff usually takes longer.</p>'
        + (f'<p class="note">Education cost sources:</p><ul class="note">{cost_notes}</ul>' if cost_notes else "")
        + f"{chart}</section>"
    )


SALARY_SOURCES = {
    "BLS median annual wage": "BLS OEWS May 2024 median annual wage (occupations)",
    "BLS median weekly earnings x 52": "BLS median weekly earnings x 52 (high school diploma, bachelor's degree)",
    "College Scorecard": "College Scorecard median earnings (schools and programs)",
}


def _salary_chart(options: list[dict]) -> str:
    """Salary comparison for the chosen rows, labeled with their sources."""
    # Only national figures belong in a chart titled median salary.
    shown = [o for o in options if not o.get("user_numbers") and o.get("expected_salary")]
    if not shown:
        return ""
    bars = [{"label": o.get("short_label") or o.get("name", ""), "value": o["expected_salary"]} for o in shown]
    sources = [
        text for key, text in SALARY_SOURCES.items()
        if any((o.get("salary_basis") or "").startswith(key) for o in shown)
    ]
    return (
        '<section><h2>Median salary by option</h2>'
        + bar_chart("Median annual salary", "Median annual salary", "Option", bars, "usd", "; ".join(sources))
        + "</section>"
    )


def _metric(value, unit: str) -> str:
    if value is None:
        return "No data"
    if unit == "bool":
        return "Yes" if value else "No"
    return _fmt(_num(value), unit)


def _metric_table(keys: list, options: list[dict]) -> str:
    keys = [k for k in keys if k in METRIC_FORMATS]
    shown = [o for o in options if any(k in (o.get("metrics") or {}) for k in keys)]
    if not keys or not shown:
        return ""
    return _table(
        ["Option"] + [METRIC_FORMATS[k][0] for k in keys],
        [[o.get("name", "")] + [_metric((o.get("metrics") or {}).get(k), METRIC_FORMATS[k][1]) for k in keys]
         for o in shown],
    )


def _section(sec: dict, options: list[dict]) -> str:
    out = [f'<section><h2>{_esc(sec.get("title", ""))}</h2>']
    bullets = sec.get("bullets") or []
    if bullets:
        out.append("<ul>" + "".join(f"<li>{_esc(b)}</li>" for b in bullets) + "</ul>")
    out.append(_metric_table(sec.get("table_metrics") or [], options))
    if sec.get("what_it_means"):
        out.append(f'<p class="means"><strong>What this means for you:</strong> {_esc(sec["what_it_means"])}</p>')
    out.append("</section>")
    return "".join(out)


CSS = """
*{box-sizing:border-box}
body{margin:0;background:#fff;color:#1f2937;font:15px/1.6 'Inter',system-ui,sans-serif}
main{max-width:920px;margin:0 auto;padding:24px 16px 48px}
h1{font-size:1.2rem;color:#6b7280;margin:0 0 8px;font-weight:600}
.headline{font-size:1.45rem;font-weight:700;line-height:1.35;margin:0 0 24px}
h2{font-size:1.15rem;margin:0 0 12px;padding-bottom:6px;border-bottom:2px solid #e5e7eb}
section{margin:0 0 32px;page-break-inside:avoid}
.tbl{overflow-x:auto;margin:0 0 16px}
table{border-collapse:collapse;width:100%;font-size:.9rem}
th,td{padding:8px 10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}
th{background:#f3f4f6;font-weight:600;white-space:nowrap}
figure{margin:0 0 16px}
figcaption{font-weight:600;margin:0 0 4px}
.src{display:block;color:#6b7280;font-size:.8rem;font-weight:400}
svg{width:100%;height:auto;font-size:12px}
svg .grid{stroke:#e5e7eb}
svg .bar{fill:#2563eb}
svg .lbl,svg .val{fill:#1f2937}
svg .tick{fill:#6b7280;font-size:11px}
svg .axis{fill:#374151;font-weight:600}
.means{background:#eff6ff;border-left:4px solid #2563eb;padding:10px 12px;margin:0}
.note{color:#4b5563;font-size:.9rem}
.notice{border-bottom:1px solid #e5e7eb;padding-bottom:12px;margin:0 0 20px;color:#374151;font-size:.9rem;font-weight:700}
footer{border-top:1px solid #e5e7eb;padding-top:12px;color:#6b7280;font-size:.8rem}
.save-btn{position:fixed;top:12px;right:12px;background:#2563eb;color:#fff;border:0;border-radius:6px;padding:8px 14px;font:600 .85rem system-ui,sans-serif;cursor:pointer}
@media print{.save-btn{display:none}section{page-break-before:auto}}
"""

SAVE_BUTTON = (
    '<button class="save-btn" onclick="(function(){var a=document.createElement(\'a\');'
    "a.href='data:text/html,'+encodeURIComponent(document.documentElement.outerHTML);"
    "a.download='next-right-step-report.html';a.click()})()\">Save Report</button>"
)


def render_report(spec: dict, rows: list[dict]) -> str:
    """rows: every option row the model could pick (options.candidate_rows).
    The report shows the ones it picked, in its order, with their own numbers."""
    by_id = {r["option_id"]: r for r in rows}
    options = [by_id[i] for i in dict.fromkeys(spec.get("option_ids") or []) if i in by_id]
    # Payoff is measured against the user's current salary when they gave one.
    baseline = by_id.get("baseline:current") or by_id.get("baseline:hs") or {}
    baseline_salary = _num(baseline.get("expected_salary"), HS_SALARY) or HS_SALARY
    baseline_label = baseline.get("name") or "High school diploma"
    sections = [s for s in spec.get("sections") or [] if isinstance(s, dict)]
    limitations = spec.get("limitations") or []

    body = [
        f'<p class="notice">{_esc(FIGURES_NOTICE)}</p>',
        "<h1>Your Next Right Step report</h1>",
        f'<p class="headline">{_esc(spec.get("headline", ""))}</p>',
    ]
    body.append(_salary_chart(options))
    body.extend(_section(s, options) for s in sections)
    body.append(_financial_section(options, baseline_salary, baseline_label))
    if limitations:
        body.append(
            "<section><h2>Limitations</h2><ul>"
            + "".join(f"<li>{_esc(item)}</li>" for item in limitations)
            + "</ul></section>"
        )
    body.append(f"<footer>{_esc(DISCLAIMER.format(today=date.today().strftime('%B %d, %Y')))}</footer>")

    return (
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        "<title>Next Right Step Report</title>"
        '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">'
        f"<style>{CSS}</style></head><body>{SAVE_BUTTON}<main>{''.join(body)}</main></body></html>"
    )
